Update installation for Windows, missing sudo
jekyll/jekyll pull request #7622
Opened 2019-04-18 17:10 UTC by JarekKala

## Summary

## Context

2019-04-18 17:13 UTC, ashmaroli commented
@JarekKala  The Core Team has always advocated the "no sudo" policy. Why do you think its necessary..?

2019-04-18 18:33 UTC, JarekKala commented
@ashmaroli I needed it to run it when I did these steps. I got error:

ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.5.0 directory

I also needed sudo for next step so maybe I did something wrong.

2019-04-18 19:02 UTC, ashmaroli commented
@JarekKala You may have to follow the steps outlined in the PR #7167:
> [configure `gem`](https://jekyllrb.com/docs/troubleshooting/#no-sudo) so that packages are installed in your $HOME directory so `sudo` is not required.  Add the following to the bottom of your .bashrc file:
>
> ```sh
> # Ruby exports
>
> export GEM_HOME=$HOME/gems
> export PATH=$HOME/gems/bin:$PATH
> ```
>
>Then reload it:
>
> ```sh
> source .bashrc
> ```

Please try the above and let us know.. Thanks.

2020-12-01 14:36 UTC, MichaelCurrin requested changes

2020-12-01 14:36 UTC, MichaelCurrin commented on docs/_docs/installation/windows.md
> +sudo gem update
The install step below is done _without_ sudo, therefore this should also exclude it.

In fact, if you need permissions errors, there are at least two solutions without using `sudo`:

- Change the permissions of the shared gems folder (`/usr/.../...`) to be editable by all users.
- Use `gem update --user-install` and `gem install GEM_NAME --user-install` to install to the user's `~/.gem` directory.

This is a complex topic - in fact `--user-install` may become an implied optional in newer `gem` command.

So it is best to leave this as it was.

2020-12-01 14:39 UTC, MichaelCurrin commented on docs/_docs/installation/windows.md
> +sudo gem update
```
gem update --help

...
        --[no-]user-install          Install in user's home directory instead
                                     of GEM_HOME.
```

2024-09-15 14:46 UTC, closed without merging