Adding handling of collections_dir
jekyll/jekyll pull request #8361
Opened 2020-08-27 19:04 UTC by alexander-morris

I painstakingly discovered that when the specified directory's name contains '_' or is exactly the word 'collections' then _posts will not be read while contained within it.

Just hoping to share it to help others avoid the same pitfall. :) 

## Summary

## Context

2020-08-28 09:38 UTC, ashmaroli requested changes
The proposed changes cannot be accepted as they are incorrect:
- **`collections_dir` can be named `"collections"` and can contain `_`**.
Just that it cannot start with the characters `.` / `_` / `#` / `~`
- `collections_dir` does not have an associated command-line switch. So, there is no reason to document the setting in this table or in this document entirely

2020-08-28 12:50 UTC, alexander-morris commented
Hey @ashmaroli - thanks for the quick reply. 

I can definitely move this note elsewhere and remove the command-line switch.

I'm not sure about the 'collections' title though. In my case, when it is called 'collections', the _posts directory within it is not read.

2020-08-28 12:56 UTC, ashmaroli commented
> In my case, when it is called 'collections', the _posts directory within it is not read.

We already have a test for it:
https://github.com/jekyll/jekyll/blob/badc9c2d30e6b34a97ccdb0f20b1635e1aea575d/features/collections_dir.feature#L6-L18

2020-09-16 16:30 UTC, MichaelCurrin commented
My comments are similar to those above.

The change looks out of place as I would expect a 1:1 mapping between sections on the left and arguments on the right. This extra row is not a new argument but just a note on an _existing_ argument.

I suggest rather update this section:

```
Site Source

Change the directory where Jekyll will read files
```

to say:

```
Site Source

Change the directory where Jekyll will read files.

If you have a collections directory e.g. `my_collection`, it must be inside this source directory. It may not be named 'collections' and may not start with `.`,  `_`, `#` or `~`.
```

I don't think if the `_posts` part is relevant. The name rule stands alone without caring about `_posts` is inside it (which is not an antipattern)

2021-05-18 07:36 UTC, closed without merging