Add Arengu to form services list documentation
jekyll/jekyll pull request #8414
Opened 2020-09-26 12:48 UTC by jacobovidal

Add Arengu to form services list documentation

2020-12-01 14:30 UTC, MichaelCurrin requested changes

2020-12-01 14:30 UTC, MichaelCurrin commented on docs/pages/resources.md
> +  - [Arengu] (https://www.arengu.com)
```suggestion
  - [Arengu](https://www.arengu.com)
```

Whitespace is invalid so I removed. Check the markdown view to see how it looks with whitespace

https://github.com/jekyll/jekyll/blob/7356006d7019dbcd038212bd18a2d83d7f7f11cd/docs/pages/resources.md#forms

2020-12-02 10:07 UTC, MichaelCurrin approved these changes

2020-12-02 13:12 UTC, DirtyF commented
@MichaelCurrin if you're interested in joining the Documentation team please join on https://teams.jekyllrb.com

2020-12-02 13:12 UTC, DirtyF approved these changes

2020-12-02 13:12 UTC, merged

2020-12-02 16:24 UTC, MichaelCurrin commented
Thanks @DirtyF for the link. I hadn't seen that site before.

I've joined

2020-12-02 16:27 UTC, ashmaroli commented
Welcome aboard @MichaelCurrin! Great to have you as part of the Team!