Fixing "Built-in formats"
jekyll/jekyll pull request #8995
Opened 2022-03-14 02:19 UTC by EmilySeville7cfg

- global permalink doesn't have `output_ext` placeholder as documentation above tells
- wrong `W:` removed

## Summary

## Context

2022-03-14 02:24 UTC, EmilySeville7cfg commented
This is my attemp to write regex for:
- global permalink: `^((/(:(year|short_year|month|i_month|short_month|long_month|day|i_day|y_day|w_year|week|w_day|short_day|long_day|hour|minute|second|title|slug|categories|slugified_categories))+)+|date|pretty|ordinal|weekdate|none)$`
- collection permalink: `^(/(:(collection|path|name|title|output_ext))+)+$`

2022-03-17 19:20 UTC, mattr- approved these changes
looks good to me

2022-03-17 19:23 UTC, mattr- commented
I went to go double check the code and now I'm confused. The documentation mirrors the code exactly. When you use these permalink styles on a site, are you seeing different results?

2022-03-18 01:15 UTC, EmilySeville7cfg commented
1. There is an [example](https://jekyllrb.com/docs/permalinks/#global): `permalink: /:categories/:year/:month/:day/:title:output_ext`. But in [this](https://jekyllrb.com/docs/permalinks/#placeholders) placeholder list no `output_ext` is listed.

2. [Here](https://jekyllrb.com/docs/permalinks/#built-in-formats) is an example: `/:categories/:year/W:week/:short_day/:title:output_ext` but my regex can't catch `W:` and rejects this value.

2022-03-21 09:47 UTC, ashmaroli requested changes
Blocking this since docs should mirror Ruby codebase.

2022-03-21 09:55 UTC, ashmaroli commented
> * There is an [example](https://jekyllrb.com/docs/permalinks/#global): `permalink: /:categories/:year/:month/:day/:title:output_ext`. But in [this](https://jekyllrb.com/docs/permalinks/#placeholders) placeholder list no `output_ext` is listed.

Agreed. But it is mentioned under [subsequent section towards end of page](https://jekyllrb.com/docs/permalinks/#collections)
Perhaps this pull request may add the missing placeholder to the global table..


> * [Here](https://jekyllrb.com/docs/permalinks/#built-in-formats) is an example: `/:categories/:year/W:week/:short_day/:title:output_ext` but my regex can't catch `W:` and rejects this value. What is `W:`? I found no information about is.

`W` will act as a prefix to placeholder `:week`.
For example, `W10`..

Agreed that it has not been documented anywhere. Perhaps this pull request could add that info..

2022-04-03 11:48 UTC, EmilySeville7cfg commented
> W will act as a prefix to placeholder :week.

What placeholder prefixes are allowed?

2022-04-03 12:16 UTC, ashmaroli commented
> What placeholder prefixes are allowed?

@EmilySeville7cfg See underlying code for reference:
https://github.com/jekyll/jekyll/blob/19868d5602120fe4257be1a01791be0b0686f1a5/lib/jekyll/configuration.rb#L272-L278

Built-ins are syntactic-sugars (or shorthands) to a particular implementation.
So, `weekdate` is a shorthand to a particular template: `/:categories/:year/W:week/:short_day/:title:output_ext`, i.e. no other prefix supported. If one does not want that `W`, they'll have to manually write the template without the `W`.

---

P.S. You may add a note to reduce confusion.. Also, please update the PR title and description to better describe latest diff.

2022-04-03 14:32 UTC, ashmaroli commented on docs/_docs/permalinks.md
> +        <small>`W` is a prefix for `:week`</small>
```suggestion
        <p>
          <code>/:categories/:year/W:week/:short_day/:title:output_ext</code></br>
          <small>`W` is a prefix for `:week`</small>
        </p>
```

2022-04-08 14:20 UTC, ashmaroli approved these changes

2022-04-08 14:22 UTC, ashmaroli commented
Thanks @EmilySeville7cfg
@jekyllbot: merge +doc

2022-04-08 14:22 UTC, merged